---
# from https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups
# IMPORTANT: end all entries with ":" otherwise you'll have strange effects

all:
  hosts:
    127.0.0.1:
  children:
    windows:
      hosts:
        192.168.0.1:
        192.168.0.2:
        192.168.0.3:
    dbservers:
      hosts:
        192.168.3.1:
        192.168.3.2:
        192.168.3.3:
    east:
      hosts:
        192.168.90.21:
        192.168.90.22:
        192.168.90.23:
    west:
      hosts:
        192.168.17.101:
        192.168.17.102:
        192.168.17.103:
    prod:
      children:
        east:
        windows:
        dbservers:
    test:
      children:
        west:
