- name: Reset all user accounts
  hosts: windows
  gather_facts: no
  
  tasks:
    - include_tasks: tasks/win_user_delete.yml
    - include_tasks: tasks/win_user_create.yml
    - include_tasks: tasks/win_disable_newuser_oobe.yml
 
