- name: Complete windows machine setup and customization
  hosts: windows
  gather_facts: no
  serial: 3

  tasks:
    # system settings like localization
    - include_tasks: tasks/win_region.yml
    - include_tasks: tasks/win_timezone.yml
    # network settings
    - include_tasks: tasks/win_dns.yml
    - include_tasks: tasks/win_firewall.yml
    #- include: tasks/win_network_profile.yml # does not work yet
    # other settings
    - include_tasks: tasks/win_powerplan.yml
    - include_tasks: tasks/win_disable_newuser_oobe.yml
    - include_tasks: tasks/win_student_create.yml
    # install software
    - include_tasks: tasks/win_choco.yml
    - include_tasks: tasks/win_choco_update_all.yml
    - include_tasks: tasks/win_choco_software_packages.yml
    # windows updates
    - include_tasks: tasks/win_update_service.yml
    - include_tasks: tasks/win_updates_install.yml
