- name: Reset all student user accounts
  hosts: windows
  tasks:
    - include: tasks/win_student_delete.yml
    - include: tasks/win_student_create.yml
    - include: tasks/win_disable_newuser_oobe.yml
 
