- name: Reset all student user accounts
  hosts: windows
  gather_facts: no
  
  tasks:
    - include_tasks: tasks/win_student_delete.yml
    - include_tasks: tasks/win_student_create.yml
    - include_tasks: tasks/win_disable_newuser_oobe.yml
 
