---
- name: Install Windows updates on all machines and reboot if needed
  hosts: windows
  gather_facts: no
  #serial: 1
  # will break if that single machine is unreachable
  #ignore_errors: true
  
  tasks:
    - include_tasks: tasks/win_updates_install.yml
