- name: Download cygwin installer
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
  ansible.builtin.get_url:
    url: https://www.cygwin.com/setup-x86_64.exe
    dest: c:\Windows\Temp\cygwin_setup-x86_64.exe

- name: Install and update all packages
  # https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_shell_module.html
  ansible.windows.shell: c:\Windows\Temp\cygwin_setup-x86_64.exe --quiet --upgrade-also --packages ansible
  
