- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  win_chocolatey:
    name: chocolatey

- name: Deactivate choco install prompt
  ansible.windows.win_shell: choco feature enable -n allowGlobalConfirmation

- name: Activate automatic choco upgrade all
  win_chocolatey:
    name: choco-upgrade-all-at-startup
    state: present
