---
# https://docs.ansible.com/ansible/latest/modules/win_chocolatey_module.html#win-chocolatey-module

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    force: true
    state: present
  loop:
  - procexp
  - putty
  - windirstat
  - firefox
  - google-chrome-x64
  - notepadplusplus
  - adobereader
  - zoom
  - vmware-horizon-client
  - bginfo

- name: Uninstall multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: absent
  loop:
  - skype
  - teamviewer.host
