---
# https://docs.ansible.com/ansible/2.9/modules/win_chocolatey_module.html#win-chocolatey-module

- name: Remove all installed choco packages
  win_chocolatey:
    # task will fail if no choco packages are installed (e.g. clean install)
    name: all
    force: true
    state: absent

# remove chocolatey itself
# https://docs.chocolatey.org/en-us/choco/uninstallation
- name: Remove chocolatey folder
  win_file:
    path: C:\ProgramData\chocolatey
    state: absent
