# https://docs.ansible.com/ansible/2.9/modules/win_package_module.html

- name: Create user account
  win_user:
    name: "{{ username }}"
    fullname: User Account
    description: User Account
    state: present
    password: "{{ userpass }}"
    groups:
      - "{{ usergroups }}"
    password_expired: false
    password_never_expires: true
    account_disabled: false
    account_locked: false
