---
# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_copy_module.html

- name: Copy {{ transfer_source }} to {{ transfer_target }} on Ansible target
  win_copy:
    # do not use a trailing slash if you want to copy a complete subfolder (with its content)
    src: "{{ transfer_source }}"
    dest: "{{ transfer_target }}"
