# https://docs.ansible.com/ansible/2.9/modules/win_chocolatey_module.html#win-chocolatey-module

- name: Update all installed choco packages
  win_chocolatey:
    name: all
    state: latest
    # task will fail if no choco packages are installed (e.g. clean install)
    ignore_errors: true
